development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: mccombs_development
  pool: 5
  host: localhost
  # username: root


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: mccombs_test
  pool: 5
  host: localhost
  # username: root

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: mccombs_production
  pool: 5
  host: localhost
  # username: root
