development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hourschool_greendoors_development
  pool: 5
  host: localhost
  # username: root


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hourschool_greendoors_test
  pool: 5
  host: localhost
  # username: root

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hourschool_greendoors_production
  pool: 5
  host: localhost
  # username: root
